app/urls.py
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    
    path('releve/',views.Releve_Bank,name="bank1"),
    path('', views.Filter_Releves_By_Date, name='filter_releves_by_date'),
    path('inv', views.invoice , name='inv' ),
    path('upload', views.upload_pdf_form, name='upload_pdf_form'),
    path('save_match/', views.save_match, name='save_match'),
    path('view/', views.view_matches, name='view_matches'),
    path('update_sms/<int:pk>/', views.update_sms, name='update_sms'),
    path('update_releve/<int:pk>/', views.update_releve, name='update_releve'),
    path('update_inv/<int:pk>/', views.update_inv, name='update_inv'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

odoo/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.
class Date(models.Model):
    date = models.DateField(unique=True)

    def __str__(self):
        return str(self.date)

class RELEVE(models.Model):
    pdf = models.FileField(upload_to='pdf_forms/%Y/%m/%d/')
    date = models.ForeignKey(Date, on_delete=models.CASCADE, related_name='releves' , null=True)
    Date_operation = models.DateField(null=True)
    Date_valeur = models.DateField(null=True)
    Reference = models.CharField(max_length=250, null=True)
    Nature_operation = models.CharField(max_length=250, null=True)
    Montant_debit = models.CharField(max_length=250, null=True)
    Montant_credit = models.CharField(max_length=250, null=True)

    def __str__(self):
        return f"{self.Nature_operation}"
    

class Sms(models.Model):
    service = models.CharField(max_length=250, null=True)
    date = models.TextField(null=True)
    amount = models.CharField(max_length=250, null=True)
    date_f = models.ForeignKey(Date, on_delete=models.CASCADE, related_name='sms', null=True)

    def __str__(self):
        return f"{self.service} - {self.date} - {self.amount}"
    

class ExtractedInfo(models.Model):
    pdf = models.FileField(upload_to='pdf_forms/%Y/%m/%d/') 
    service = models.CharField(max_length=250)
    date = models.CharField(max_length=250 ,null=True)
    amount = models.CharField(max_length=250)
    date_f = models.ForeignKey(Date, on_delete=models.CASCADE, related_name='extracted_infos', null=True)    

    def __str__(self):
        return f"{self.service} - {self.date} - {self.amount}"

class Client(models.Model):
    name = models.CharField(max_length=100)

class Match(models.Model):
    #client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='matches', null=True, blank=True)  # Assuming you have a Client model
    releve = models.ForeignKey(RELEVE, on_delete=models.CASCADE, related_name='matches')
    sms = models.ForeignKey(Sms, on_delete=models.CASCADE, related_name='matches', null=True, blank=True)
    facture = models.ForeignKey(ExtractedInfo, on_delete=models.CASCADE, related_name='matches', null=True, blank=True)
    date = models.ForeignKey(Date, on_delete=models.CASCADE, related_name='matches', null=True)
    status = models.CharField(max_length=255, default='Pending') 

    def __str__(self):
        return f"Match for RELEVE {self.releve.id}"

templates/Releve/releve.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Upload Bank Statements</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
        h1 {
            color: #333;
            text-align: center;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
            background-color: #f9f9f9;
            border-radius: 5px;
            padding: 20px;
            border: 1px solid #ddd;
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }

        input[type="file"] {
            margin-bottom: 10px;
        }

        button[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }

        h2 {
            margin-top: 20px;
            text-align: center;
            color: #333;
        }

        .filter-form {
            text-align: center;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'filter_releves_by_date' %}">HOME</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'bank1' %}">Relevé bancaire</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'upload_pdf_form' %}">Facture</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inv' %}">SMS</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <h1>Upload Bank Statement</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_pdf">Select Bank Statement PDF:</label><br>
            {{ form.as_p }}
            <label for="id_date">Select Date:</label><br>
            {{ date_filter_form.as_p }}
            <button type="submit">Upload</button>
        </form>
    </div>


</body>

</html>

templates/Releve/releve_form.html
<!DOCTYPE html>
<html lang="en">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create/Update INVOICE</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
        }

        h2 {
            text-align: center;
            margin-top: 20px;
            color: #343a40;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #fff;
        }

        form input[type="text"],
        form input[type="date"],
        form select {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        form button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            margin-top: 10px;
        }

        form button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'filter_releves_by_date' %}">HOME</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'bank1' %}">Relevé bancaire</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'upload_pdf_form' %}">Facture</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inv' %}">SMS</a>
                </li>
            </ul>
        </div>
    </nav>
    <h2>{{ form.instance.pk|default_if_none:"ADD" }} Releve</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="btn">Submit</button>
    </form>
</body>

</html>